config/routes.rb
Rails.application.routes.draw do
  resources :kimatus
  resources :gakuseis
  get 'messages/index'
  get 'messages', to: 'messages#index'
  
  get 'messages/add'
  post 'messages/add', to: 'messages#create'
  
  get 'messages/edit/:id', to: 'messages#edit'
  patch 'messages/edit/:id', to: 'messages#update'
  
  get 'messages/delete/:id', to: 'messages#delete'
  get 'messages/:id', to: 'messages#show'
  
  get 'people/find'
  post 'people/find'
  
  post "cards/add"
  get 'cards/index'
  get 'cards/show/:id' ,to: "cards#show"
  get 'cards/add'
  get 'cards/edit/:id' ,to: "cards#edit"
  patch "cards/edit/:id" ,to: "cards#edit"
  get 'cards/delete/:id' ,to: "cards#delete"
 
  resources :books
  get 'students/index'
  get 'students/show/:id',to: "students#show"
  get 'students/add'
  post 'students/create'
  get 'students/edit/:id',to: "students#edit#"
  patch 'students/edit/:id',to: "students#update"

  resources :items
  get 'people/delete/:id', to: 'people#delete'
  get 'people/edit/:id', to: 'people#edit'
  patch 'people/edit/:id', to: 'people#update'
  get 'people/add'
  post "people/add" , to: "people#create"
  get 'people/index'
  get "people", to: "people#index"
  get 'people/:id', to: 'people#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "hello/index"
  post "hello/index"
  get "hello/other"

  get "aisatsu/myname"
  post "aisatsu/myname"
  
  get "aisatsu/calc"
  post "aisatsu/calc"
  
  get "aisatsu", to: "aisatsu#myname"
  get "aisatsu/keisan"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/gakusei.rb
class Gakusei < ApplicationRecord
    validates :name,presence: true
    validates :name,length: {maximum: 10}
    validates :age,numericality: {greater_than_or_equal_to: 18 } 
    validates :gakusei_no,uniqueness: true 
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/kimatu.rb
class Kimatu < ApplicationRecord
    validates :kokugo,numericality: {greater_than_or_equal_to: 0,less_than_or_equal_to: 100} 
    validates :sugaku,numericality: {greater_than_or_equal_to: 0,less_than_or_equal_to: 100} 
    validates :eigo,numericality: {greater_than_or_equal_to: 0,less_than_or_equal_to: 100} 
    validates :kbn,inclusion: {in: [ 1, 2]}


end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :person
end

app/models/person.rb
class Person < ApplicationRecord
    has_many :message
    validates :name,presence: {message: "名前は必須入力です"}
    validates :age,numericality: {message: "年齢は数字で入力してください"}
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :price)
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  layout "cards"
  def index
    @cards = Card.all
  end
  def show
    @card = Card.find(params[:id]) 
  end
  def add
    if request.post?
      Card.create(card_params)
      goback
    else
      @card = Card.new
    end
  end
  def edit
    @card = Card.find(params[:id])
    if request.patch?
      @card.update(card_params)
      goback
    end
  end
  def delete
    Card.find(params[:id]).destroy
    goback
  end

private
  def card_params
    params.require(:card).permit(:title,:author,:price,:publisher,:memo)
  end
  def goback
    redirect_to "/cards/index"
  end
end

app/controllers/kimatus_controller.rb
class KimatusController < ApplicationController
  before_action :set_kimatu, only: %i[ show edit update destroy ]

  # GET /kimatus or /kimatus.json
  def index
    @kimatus = Kimatu.all
  end

  # GET /kimatus/1 or /kimatus/1.json
  def show
  end

  # GET /kimatus/new
  def new
    @kimatu = Kimatu.new
  end

  # GET /kimatus/1/edit
  def edit
  end

  # POST /kimatus or /kimatus.json
  def create
    @kimatu = Kimatu.new(kimatu_params)

    respond_to do |format|
      if @kimatu.save
        format.html { redirect_to kimatu_url(@kimatu), notice: "Kimatu was successfully created." }
        format.json { render :show, status: :created, location: @kimatu }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kimatu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kimatus/1 or /kimatus/1.json
  def update
    respond_to do |format|
      if @kimatu.update(kimatu_params)
        format.html { redirect_to kimatu_url(@kimatu), notice: "Kimatu was successfully updated." }
        format.json { render :show, status: :ok, location: @kimatu }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kimatu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kimatus/1 or /kimatus/1.json
  def destroy
    @kimatu.destroy

    respond_to do |format|
      format.html { redirect_to kimatus_url, notice: "Kimatu was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kimatu
      @kimatu = Kimatu.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kimatu_params
      params.require(:kimatu).permit(:gakusei_id, :kbn, :kokugo, :sugaku, :eigo)
    end
end

app/helpers/aisatsu_helper.rb
module AisatsuHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/gakuseis_helper.rb
module GakuseisHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/kimatus_helper.rb
module KimatusHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/kimatus/_form.html.erb
<%= form_with(model: kimatu, local: true) do |form| %>
  <% if kimatu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kimatu.errors.count, "error") %> prohibited this kimatu from being saved:</h2>

      <ul>
        <% kimatu.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :gakusei_id %>
    <%= form.number_field :gakusei_id %>
  </div>

  <div class="field">
    <%= form.label :kbn %>
    <%= form.number_field :kbn %>
  </div>

  <div class="field">
    <%= form.label :kokugo %>
    <%= form.number_field :kokugo %>
  </div>

  <div class="field">
    <%= form.label :sugaku %>
    <%= form.number_field :sugaku %>
  </div>

  <div class="field">
    <%= form.label :eigo %>
    <%= form.number_field :eigo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/kimatus/edit.html.erb
<h1>Editing Kimatu</h1>

<%= render 'form', kimatu: @kimatu %>

<%= link_to 'Show', @kimatu %> |
<%= link_to 'Back', kimatus_path %>

app/views/kimatus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kimatus</h1>

<table>
  <thead>
    <tr>
      <th>Gakusei</th>
      <th>Kbn</th>
      <th>Kokugo</th>
      <th>Sugaku</th>
      <th>Eigo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kimatus.each do |kimatu| %>
      <tr>
        <td><%= kimatu.gakusei_id %></td>
        <td><%= kimatu.kbn %></td>
        <td><%= kimatu.kokugo %></td>
        <td><%= kimatu.sugaku %></td>
        <td><%= kimatu.eigo %></td>
        <td><%= link_to 'Show', kimatu %></td>
        <td><%= link_to 'Edit', edit_kimatu_path(kimatu) %></td>
        <td><%= link_to 'Destroy', kimatu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kimatu', new_kimatu_path %>

app/views/kimatus/new.html.erb
<h1>New Kimatu</h1>

<%= render 'form', kimatu: @kimatu %>

<%= link_to 'Back', kimatus_path %>

app/views/kimatus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gakusei:</strong>
  <%= @kimatu.gakusei_id %>
</p>

<p>
  <strong>Kbn:</strong>
  <%= @kimatu.kbn %>
</p>

<p>
  <strong>Kokugo:</strong>
  <%= @kimatu.kokugo %>
</p>

<p>
  <strong>Sugaku:</strong>
  <%= @kimatu.sugaku %>
</p>

<p>
  <strong>Eigo:</strong>
  <%= @kimatu.eigo %>
</p>

<%= link_to 'Edit', edit_kimatu_path(@kimatu) %> |
<%= link_to 'Back', kimatus_path %>